name: Makefile CI

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '**.md'
      - '*.txt'
      - '.gitignore'
      - 'docs/*'
      - 'build/*'
      - 'util/*'
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - '**.md'
      - '*.txt'
      - '.gitignore'
      - 'docs/*'
      - 'build/*'
      - 'util/*'
  workflow_dispatch:

jobs:
  linux-qvm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: build
        working-directory: build/linux-qvm
        run: |
          make

      - uses: actions/upload-artifact@v4
        with:
          name: qvm
          path: build/linux-qvm/zz-osp-pak8be.pk3
          if-no-files-found: error
          retention-days: 5